#!/bin/bash

echo "================================================"
echo "Supabase Workspaces Table Setup Guide"
echo "================================================"
echo ""
echo "The workspaces table needs to be created in your Supabase project."
echo ""
echo "1. Open your Supabase project dashboard:"
echo "   https://app.supabase.com/project/vzzbbammipjvxveqiwel"
echo ""
echo "2. Navigate to SQL Editor (left sidebar)"
echo ""
echo "3. Click 'New Query'"
echo ""
echo "4. Copy the SQL from: supabase-migrations/001-create-workspaces-table.sql"
echo ""
echo "5. Paste it into the SQL editor"
echo ""
echo "6. Click 'Run'"
echo ""
echo "After running the migration:"
echo "- Check that 'workspaces' table appears in the Tables section"
echo "- Try creating a workspace in the app"
echo "- If it still fails, check the browser console for the actual error"
echo ""
echo "================================================"
